### ISSUE TITLE
We need more Metrics 

### ISSUE THREAD

**Issue by SadCheeto** [Faurby/BlackOps#126]
1: Antal messages (✔️ )
2: Antal Users (✔️ )
3: Antal følgere pr. user avg (:heavy_check_mark:)
4: Person med flest følgere (:x:)
5: Person med færrest følgere (:x:)
6: CPU stuff (:heavy_check_mark: )
7: Downtime
8: MongoDB stuff? Plads i brug??
9: Loading time på frontpage (:heavy_check_mark: )
10: Active users (user who has posted a message within a week?)

**Comment by AntonFriis** [comment]
edit: 3: Antal følgere pr. user avg (heavy_check_mark)
