### ISSUE TITLE
Section 3.1 Developer interaction

### ISSUE THREAD

**Issue by SadCheeto** [Faurby/BlackOps#167]
REMEMBER TO REFLECT IN THIS SECTION!!!

What went well? 

What did not?

Github Issues used for tracking things we needed to do

**Comment by SadCheeto** [comment]
Github issues should not be explained in depth, as section 3.2 will go into detail about this

**Comment by SadCheeto** [comment]
pls read through and comment for changes

**Comment by Faurby** [comment]
have looked through and fixed "småting"
