### ISSUE TITLE
Add working timestamps to tweets

### ISSUE THREAD

**Issue by AntonBertelsen** [Faurby/BlackOps#37]

**Comment by Faurby** [comment]
Seems that timestamps are 000000 on the VM, figure out how to fix

**Comment by Faurby** [comment]
![billede](https://user-images.githubusercontent.com/37332429/155034491-e8714d28-3fa8-47dc-a18d-870faee00d04.png)

Seems to be working on the VM? Can you check if it works on your local machine @AntonBertelsen , otherwise I think we can close it.

**Comment by AntonFriis** [comment]
Currently works by using the servers local time (france), instead maybe take the users local time so it matches up with the users device.

**Comment by Faurby** [comment]
True, but also not great since you could see posts from the "future" if user is in e.g. Australia hahha. I hate timezones...
