### ISSUE TITLE
sim API

### ISSUE THREAD

**Issue by Faurby** [Faurby/BlackOps#38]
https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_03/API%20Spec/minitwit_sim_api.py

do like this, run test also maybe

**Comment by FrederikRothe** [comment]
SimController endpoints


#1
sim/latest [GET]

Return latest msg?

return jsonify({"latest": LATEST})

---------

#2
sim/register [POST]

Register user.

----------

#3
sim/msgs [GET]

Select all messages and send em back.

----------

#4
sim/msgs/<username> [GET] & [POST]

Select all messages from specific user


----------

#5
sim/fllws/<username> [GET] & [POST]

Select all following users from a given user.

----------
