### ISSUE TITLE
Create CI/CD setup

### ISSUE THREAD

**Issue by SadCheeto** [Faurby/BlackOps#60]
Until next week, create a CI/CD setup for your ITU-MiniTwit development.

You can freely choose your CI/CD system. BSc students are likely best served by adapting the example from the scenario from [Today's Exercises](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_04/README_EXERCISE.md). But in essence everybody can choose freely.

OBS MSc students: Remember to log and provide good arguments for the choice of CI/CD system, i.e., why do you choose your solution instead of any other?

You choose freely if you want to go for continuous delivery or continuous deployment.

Let your build pipeline contain not only building your application but also execution of your test suite and other appropriate build stages.

From now on create the (at least weekly) releases on Github automatically. Release that version of your ITU-MiniTwit that is in production.

**Comment by Faurby** [comment]
Shoulddddd work, but a good idea to test it. Preferably while I explain what I've done

**Comment by SadCheeto** [comment]
Initial ci/cd has been created and tested. Everything works
