### ISSUE TITLE
Find a way to store password hashed

### ISSUE THREAD

**Issue by Faurby** [Faurby/BlackOps#9]
Right now we store passwords in plaintext, very bad

**Comment by AntonBertelsen** [comment]
Passwords are now hashed with PBKDF2
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rfc2898derivebytes?view=net-6.0

Each user has a unique salt stored in plain text to prevent hackers from looking up common passwords in a hash dictionary
